version: '3.8'

services:
  expo-app:
    build: .
    container_name: tapabc_expo
    restart: unless-stopped
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    environment:
      # Força o uso do túnel e desabilita verificações chatas
      EXPO_USE_TUNNEL: "true"
      EXPO_SKIP_VERSION_CHECK: "1"
      NODE_OPTIONS: "--max-old-space-size=512"   # evita problemas de memória em máquinas pequenas
    dns:
      - 8.8.8.8       # DNS do Google (funciona em qualquer lugar)
      - 8.8.4.4
    stdin_open: true
    tty: true
    command: ["npx", "expo", "start", "--tunnel", "--clear"]